#include "RiverX86Disassembler.h"

#include "CodeGen.h"

/* =========================================== */
/* Disassembly tables                          */
/* =========================================== */

RiverX86Disassembler::DisassembleOpcodeFunc RiverX86Disassembler::disassembleOpcodes[2][0x100] = {
		{
			/*0x00*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x04*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_ES>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_ES>,
			/*0x08*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x0C*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_CS>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_EXT, RIVER_FLAG_PFX>,

			/*0x10*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x14*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_SS>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_SS>,
			/*0x18*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x1C*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_DS>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_DS>,

			/*0x20*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x24*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleSegInstr<RIVER_MODIFIER_ESSEG>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>,
			/*0x28*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x2C*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleSegInstr<RIVER_MODIFIER_CSSEG>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>,

			/*0x30*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x34*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleSegInstr<RIVER_MODIFIER_SSSEG>, &RiverX86Disassembler::DisassembleDefault2RegInstr<RIVER_REG_AL, RIVER_REG_AH, RIVER_MODIFIER_O8>,
			/*0x38*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x3C*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleSegInstr<RIVER_MODIFIER_DSSEG>, &RiverX86Disassembler::DisassembleDefault2RegInstr<RIVER_REG_AL, RIVER_REG_AH, RIVER_MODIFIER_O8>,

			/*0x40*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>,
			/*0x44*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x40>,
			/*0x48*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>,
			/*0x4C*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x48>,

			/*0x50*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>,
			/*0x54*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x50>,
			/*0x58*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>,
			/*0x5C*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x58>,

			/*0x60*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x64*/ &RiverX86Disassembler::DisassembleSegInstr<RIVER_MODIFIER_FSSEG>, &RiverX86Disassembler::DisassembleSegInstr<RIVER_MODIFIER_GSSEG>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O16, RIVER_FLAG_PFX>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_A16, RIVER_FLAG_PFX>,
			/*0x68*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x6C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x70*/ &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>,
			/*0x74*/ &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>,
			/*0x78*/ &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>,
			/*0x7C*/ &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>,

			/*0x80*/ &RiverX86Disassembler::DisassembleExtInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleExtInstr, &RiverX86Disassembler::DisassembleExtInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleExtInstr,
			/*0x84*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x88*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x8C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x90*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>,
			/*0x94*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>, &RiverX86Disassembler::DisassemblePlusRegInstr<0x90>,
			/*0x98*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x9C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0xA0*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleDefaultSecondRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultSecondRegInstr<RIVER_REG_xAX>,
			/*0xA4*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0xA8*/ &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_AL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultRegInstr<RIVER_REG_xAX>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_OPSIZE_8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0xAC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,

			/*0xB0*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>,
			/*0xB4*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB0, RIVER_MODIFIER_O8>,
			/*0xB8*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>,
			/*0xBC*/ &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>, &RiverX86Disassembler::DisassemblePlusRegInstr<0xB8>,

			/*0xC0*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<0, RIVER_FLAG_BRANCH | RIVER_MODIFIER_O16>, &RiverX86Disassembler::DisassembleDefaultInstr<0, RIVER_FLAG_BRANCH>,
			/*0xC4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0xC8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xCC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0xD0*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultSecondRegInstr<RIVER_REG_CL, RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultSecondRegInstr<RIVER_REG_CL>,
			/*0xD4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xD8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xDC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0xE0*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xE4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xE8*/ &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleDefaultInstr<0, RIVER_FLAG_BRANCH>, &RiverX86Disassembler::DisassembleRelJmpInstr<2>,
			/*0xEC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0xF0*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_LOCK, RIVER_FLAG_PFX>, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_REPNZ, RIVER_FLAG_PFX>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_REPZ, RIVER_FLAG_PFX>,
			/*0xF4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleSubOpInstr<disassemble0xF6Instr>, &RiverX86Disassembler::DisassembleSubOpInstr<disassemble0xF7Instr>,
			/*0xF8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xFC*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleSubOpInstr<disassemble0xFFInstr>
		}, {
			/*0x00*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x04*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x08*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x0C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x10*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x14*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x18*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x1C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x20*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x24*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x28*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x2C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x30*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x34*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x38*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x3C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x40*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x44*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x48*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0x4C*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,

			/*0x50*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x54*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x58*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x5C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x60*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x64*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x68*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x6C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x70*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x74*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x78*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0x7C*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0x80*/ &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>,
			/*0x84*/ &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>,
			/*0x88*/ &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>,
			/*0x8C*/ &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>, &RiverX86Disassembler::DisassembleRelJmpInstr<5>,

			/*0x90*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>,
			/*0x94*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>,
			/*0x98*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>,
			/*0x9C*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>,

			/*0xA0*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xA4*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xA8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xAC*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr,

			/*0xB0*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xB4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,
			/*0xB8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleExtInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xBC*/ &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr,

			/*0xC0*/ &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_MODIFIER_O8>, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xC4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleSubOpInstr<RiverX86Disassembler::disassemble0x0FC7Instr>,
			/*0xC8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xCC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0xD0*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xD4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xD8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xDC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0xE0*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xE4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xE8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xEC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,

			/*0xF0*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xF4*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xF8*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
			/*0xFC*/ &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr
		}
};

RiverX86Disassembler::DisassembleOperandsFunc RiverX86Disassembler::disassembleOperands[2][0x100] = {
	{
		/*0x00*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x01*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x02*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x03*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x04*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x05*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x06*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x07*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x08*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x09*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x0A*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x0B*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x0C*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x0D*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x0E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x0F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x10*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x11*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x12*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x13*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x14*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x15*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x16*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x17*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x18*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x19*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x1A*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x1B*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x1C*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x1D*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x1E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x1F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x20*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x21*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x22*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x23*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x24*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x25*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x26*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x27*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x28*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x29*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x2A*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x2B*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x2C*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x2D*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x2E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x2F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x30*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x31*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x32*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x33*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x34*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x35*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x36*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x37*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x38*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x39*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x3A*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x3B*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x3C*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0x3D*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0x3E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x3F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x40*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x41*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x42*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x43*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x44*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x45*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x46*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x47*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x48*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x49*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x4A*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x4B*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x4C*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x4D*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x4E*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x4F*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0x50*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x51*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x52*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x53*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x54*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x55*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x56*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x57*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x58*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x59*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x5A*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x5B*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x5C*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x5D*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x5E*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x5F*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x60*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x61*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x62*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x63*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x64*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x65*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x66*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x67*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x68*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleImm32> >,
		/*0x69*/ &RiverX86Disassembler::DisassembleRegModRMImm32,
		/*0x6A*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleImm8> >,
		/*0x6B*/ &RiverX86Disassembler::DisassembleRegModRMImm8,
		/*0x6C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x70*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x71*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x72*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x73*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x74*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x75*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x76*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x77*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x78*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x79*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x7A*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x7B*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x7C*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x7D*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x7E*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x7F*/ &RiverX86Disassembler::DisassembleImm8,
		/*0x80*/ &RiverX86Disassembler::DisassembleSubOpModRMImm8,
		/*0x81*/ &RiverX86Disassembler::DisassembleSubOpModRMImm32,
		/*0x82*/ &RiverX86Disassembler::DisassembleSubOpModRMImm8,
		/*0x83*/ &RiverX86Disassembler::DisassembleSubOpModRMImm8,
		/*0x84*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x85*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x86*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x87*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x88*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x89*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0x8A*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x8B*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x8C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x8D*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x8E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x8F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x90*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x91*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x92*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x93*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x94*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x95*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x96*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x97*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp>,
		/*0x98*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x99*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDX, &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0x9A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x9B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x9C*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleUnkOp> >,
		/*0x9D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x9E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x9F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xA0*/ &RiverX86Disassembler::DisassembleMoffs8<1>,
		/*0xA1*/ &RiverX86Disassembler::DisassembleMoffs32<1>,
		/*0xA2*/ &RiverX86Disassembler::DisassembleMoffs8<0>,
		/*0xA3*/ &RiverX86Disassembler::DisassembleMoffs32<0>,
		/*0xA4*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI, 
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleConstMemOperand<3, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI, 0x00, 
						&RiverX86Disassembler::DisassembleNoOp 
					> 
				> 
			> 
		>,
		/*0xA5*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleConstMemOperand<3, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI, 0x00,
						&RiverX86Disassembler::DisassembleNoOp
					>
				>
			>
		>,
		/*0xA6*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleConstMemOperand<3, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI, 0x00,
						&RiverX86Disassembler::DisassembleNoOp
					>
				>
			>
		>,
		/*0xA7*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleConstMemOperand<3, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSI, 0x00,
						&RiverX86Disassembler::DisassembleNoOp
					>
				>
			>
		>,
		/*0xA8*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xA9*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xAA*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00, 
					&RiverX86Disassembler::DisassembleNoOp 
				>
			>
		>,
		/*0xAB*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleNoOp
				>
			>
		>,
		/*0xAC*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleNoOp
				>
			>
		>,
		/*0xAD*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleNoOp
				>
			>
		>,
		/*0xAE*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleNoOp
				>
			>
		>,
		/*0xAF*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
				&RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDI, 0x00,
					&RiverX86Disassembler::DisassembleNoOp
				>
			>
		>,
		/*0xB0*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB1*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB2*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB3*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB4*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB5*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB6*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB7*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_8>,
		/*0xB8*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xB9*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xBA*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xBB*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xBC*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xBD*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xBE*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xBF*/ &RiverX86Disassembler::DisassembleImmOp<1, RIVER_OPSIZE_32>,
		/*0xC0*/ &RiverX86Disassembler::DisassembleSubOpModRMImm8,
		/*0xC1*/ &RiverX86Disassembler::DisassembleSubOpModRMImm8,
		/*0xC2*/ &RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleImm16> >,
		/*0xC3*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
		/*0xC4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC6*/ &RiverX86Disassembler::DisassembleModRMImm8,
		/*0xC7*/ &RiverX86Disassembler::DisassembleModRMImm32,
		/*0xC8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC9*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xBP,
				&RiverX86Disassembler::DisassembleNoOp
			>
		>,
		/*0xCA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCC*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCD*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCF*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD0*/ &RiverX86Disassembler::DisassembleSubOpModRM,
		/*0xD1*/ &RiverX86Disassembler::DisassembleSubOpModRM,
		/*0xD2*/ &RiverX86Disassembler::DisassembleSubOpModRM,
		/*0xD3*/ &RiverX86Disassembler::DisassembleSubOpModRM,
		/*0xD4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD6*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD7*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD9*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDC*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDD*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDF*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE0*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE1*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE2*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE6*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE7*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE8*/ &RiverX86Disassembler::DisassembleConstRegOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<3, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleImm32> >,
		/*0xE9*/ &RiverX86Disassembler::DisassembleImm32,
		/*0xEA*/ &RiverX86Disassembler::DisassembleImm32Imm16,
		/*0xEB*/ &RiverX86Disassembler::DisassembleImm8,
		/*0xEC*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xED*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xEE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xEF*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF0*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF1*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF2*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF6*/ &RiverX86Disassembler::DisassembleSubOpOp<RiverX86Disassembler::disassemble0xF6Op>,
		/*0xF7*/ &RiverX86Disassembler::DisassembleSubOpOp<RiverX86Disassembler::disassemble0xF7Op>,
		/*0xF8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF9*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFC*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0xFD*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0xFE*/ &RiverX86Disassembler::DisassembleSubOpModRM,
		/*0xFF*/ &RiverX86Disassembler::DisassembleSubOpOp<RiverX86Disassembler::disassemble0xFFOp>
	}, {
		/*0x00*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x01*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x02*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x03*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x04*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x05*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x06*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x07*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x08*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x09*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x0A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x0B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x0C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x0D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x0E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x0F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x10*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x11*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x12*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x13*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x14*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x15*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x16*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x17*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x18*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x19*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x1A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x1B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x1C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x1D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x1E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x1F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x20*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x21*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x22*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x23*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x24*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x25*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x26*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x27*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x28*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x29*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x2A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x2B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x2C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x2D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x2E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x2F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x30*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x31*/ &RiverX86Disassembler::DisassembleConstRegOperand<0, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
			&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDX, 
				&RiverX86Disassembler::DisassembleNoOp
			>
		>,
		/*0x32*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x33*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x34*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x35*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x36*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x37*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x38*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x39*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x3A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x3B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x3C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x3D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x3E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x3F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x40*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x41*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x42*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x43*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x44*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x45*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x46*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x47*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x48*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x49*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x4A*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x4B*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x4C*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x4D*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x4E*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x4F*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0x50*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x51*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x52*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x53*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x54*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x55*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x56*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x57*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x58*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x59*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x5A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x5B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x5C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x5D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x5E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x5F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x60*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x61*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x62*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x63*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x64*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x65*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x66*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x67*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x68*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x69*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x6F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x70*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x71*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x72*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x73*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x74*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x75*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x76*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x77*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x78*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x79*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x7A*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x7B*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x7C*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x7D*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x7E*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x7F*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0x80*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x81*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x82*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x83*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x84*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x85*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x86*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x87*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x88*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x89*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x8A*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x8B*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x8C*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x8D*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x8E*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x8F*/ &RiverX86Disassembler::DisassembleImm32,
		/*0x90*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x91*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x92*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x93*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x94*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x95*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x96*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x97*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x98*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x99*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x9A*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x9B*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x9C*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x9D*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x9E*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0x9F*/ &RiverX86Disassembler::DisassembleModRM<0>,
		/*0xA0*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xA1*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xA2*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0xA3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xA4*/ &RiverX86Disassembler::DisassembleModRMRegImm8,
		/*0xA5*/ &RiverX86Disassembler::DisassembleConstRegOperand<2, 0, RIVER_REG_CL, &RiverX86Disassembler::DisassembleModRMReg>,
		/*0xA6*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xA7*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xA8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xA9*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xAA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xAB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xAC*/ &RiverX86Disassembler::DisassembleModRMRegImm8,
		/*0xAD*/ &RiverX86Disassembler::DisassembleConstRegOperand<2, 0, RIVER_REG_CL, &RiverX86Disassembler::DisassembleModRMReg>,
		/*0xAE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xAF*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0xB0*/ &RiverX86Disassembler::DisassembleConstRegOperand<2, 0, RIVER_REG_AL, &RiverX86Disassembler::DisassembleModRMReg>,
		/*0xB1*/ &RiverX86Disassembler::DisassembleConstRegOperand<2, 0, RIVER_REG_xAX, &RiverX86Disassembler::DisassembleModRMReg>,
		/*0xB2*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xB3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xB4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xB5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xB6*/ &RiverX86Disassembler::DisassembleRegSzModRM<RIVER_OPSIZE_8>,
		/*0xB7*/ &RiverX86Disassembler::DisassembleRegSzModRM<RIVER_OPSIZE_16>,
		/*0xB8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xB9*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xBA*/ &RiverX86Disassembler::DisassembleSubOpModRMImm8,
		/*0xBB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xBC*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0xBD*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0xBE*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0xBF*/ &RiverX86Disassembler::DisassembleRegModRM,
		/*0xC0*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0xC1*/ &RiverX86Disassembler::DisassembleModRMReg,
		/*0xC2*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC6*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC7*/ &RiverX86Disassembler::DisassembleSubOpOp<RiverX86Disassembler::disassemble0x0FC7Op>,
		/*0xC8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xC9*/ &RiverX86Disassembler::DisassembleNoOp,
		/*0xCA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCC*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCD*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xCF*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD0*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD1*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD2*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD6*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD7*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xD9*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDC*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDD*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xDF*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE0*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE1*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE2*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE6*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE7*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xE9*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xEA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xEB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xEC*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xED*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xEE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xEF*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF0*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF1*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF2*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF3*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF4*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF5*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF6*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF7*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF8*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xF9*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFA*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFB*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFC*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFD*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFE*/ &RiverX86Disassembler::DisassembleUnkOp,
		/*0xFF*/ &RiverX86Disassembler::DisassembleUnkOp
	}
};

RiverX86Disassembler::DisassembleOpcodeFunc RiverX86Disassembler::disassemble0xF6Instr[8] = {
	&RiverX86Disassembler::DisassembleDefaultInstr<RIVER_OPSIZE_8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_OPSIZE_8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_OPSIZE_8>, &RiverX86Disassembler::DisassembleDefaultInstr<RIVER_OPSIZE_8>,
	&RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr
};

RiverX86Disassembler::DisassembleOperandsFunc RiverX86Disassembler::disassemble0xF6Op[8] = {
	&RiverX86Disassembler::DisassembleModRMImm8, &RiverX86Disassembler::DisassembleModRMImm8, &RiverX86Disassembler::DisassembleSubOpModRM, &RiverX86Disassembler::DisassembleSubOpModRM,
	&RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleUnkOp
};


RiverX86Disassembler::DisassembleOpcodeFunc RiverX86Disassembler::disassemble0xF7Instr[8] = {
	&RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr,
	&RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleDefaultInstr
};

RiverX86Disassembler::DisassembleOperandsFunc RiverX86Disassembler::disassemble0xF7Op[8] = {
	&RiverX86Disassembler::DisassembleModRMImm32,
	&RiverX86Disassembler::DisassembleModRMImm32,
	&RiverX86Disassembler::DisassembleSubOpModRM,
	&RiverX86Disassembler::DisassembleSubOpModRM,
	&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
		&RiverX86Disassembler::DisassembleConstRegOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDX,
			&RiverX86Disassembler::DisassembleModRM<0>
		>
	>,
	&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
		&RiverX86Disassembler::DisassembleConstRegOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDX,
			&RiverX86Disassembler::DisassembleModRM<0>
		>
	>, 
	&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
		&RiverX86Disassembler::DisassembleConstRegOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDX,
			&RiverX86Disassembler::DisassembleModRM<0>
		>
	>, 
	&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xAX,
		&RiverX86Disassembler::DisassembleConstRegOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xDX,
			&RiverX86Disassembler::DisassembleModRM<0>
		>
	>
};


RiverX86Disassembler::DisassembleOpcodeFunc RiverX86Disassembler::disassemble0xFFInstr[8] = {
	&RiverX86Disassembler::DisassembleDefaultInstr, 
	&RiverX86Disassembler::DisassembleDefaultInstr, 
	&RiverX86Disassembler::DisassembleRelJmpModRMInstr, 
	&RiverX86Disassembler::DisassembleUnkInstr,
	&RiverX86Disassembler::DisassembleRelJmpModRMInstr, 
	&RiverX86Disassembler::DisassembleUnkInstr, 
	&RiverX86Disassembler::DisassembleDefaultInstr, 
	&RiverX86Disassembler::DisassembleUnkInstr
};

RiverX86Disassembler::DisassembleOperandsFunc RiverX86Disassembler::disassemble0xFFOp[8] = {
	&RiverX86Disassembler::DisassembleSubOpModRM, 
	&RiverX86Disassembler::DisassembleSubOpModRM, 
	&RiverX86Disassembler::DisassembleConstRegOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<3, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleNoOp> >,
	&RiverX86Disassembler::DisassembleUnkOp,
	&RiverX86Disassembler::DisassembleNoOp, 
	&RiverX86Disassembler::DisassembleUnkOp, 
	&RiverX86Disassembler::DisassembleConstRegOperand<1, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, &RiverX86Disassembler::DisassembleConstMemOperand<2, RIVER_OPFLAG_IMPLICIT, RIVER_REG_xSP, 0xFC, &RiverX86Disassembler::DisassembleSubOpModRM> >,
	&RiverX86Disassembler::DisassembleUnkOp
};

RiverX86Disassembler::DisassembleOpcodeFunc RiverX86Disassembler::disassemble0x0FC7Instr[8] = {
	&RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleDefaultInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr,
	&RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr, &RiverX86Disassembler::DisassembleUnkInstr
};

RiverX86Disassembler::DisassembleOperandsFunc RiverX86Disassembler::disassemble0x0FC7Op[8] = {
	&RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleModRM<0>, &RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleUnkOp,
	&RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleUnkOp, &RiverX86Disassembler::DisassembleUnkOp
};

